# Generated by Django 3.1.2 on 2020-10-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django103_app', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='django103_app.Player'),
        ),
    ]
