# Generated by Django 3.1.2 on 2020-10-31 21:23

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_expense_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=15, validators=[app.validators.validate_does_contain_spaces]),
        ),
    ]
