# Generated by Django 3.1.2 on 2020-11-02 19:15

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201102_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(validators=[app.validators.validate_time_is_negative_or_zero], verbose_name='Time (Minutes)'),
        ),
    ]
